### ISSUE TITLE
Wolfs!

### ISSUE THREAD

**Issue by matthew4444** [EpicSteve33/SurvivalGames#18] opened 2016-04-25 23:58 UTC
working on a peyts plugin,ask if u need any help with plugin

**Comment by EpicSteve33** [comment] 2016-04-26 00:16
well this is a ImgicalMine Plugin would any of your code help us?

**Comment by EpicSteve33** [comment] 2016-04-26 00:26
@matthew4444 well if you can help us then you should do it, but the wolfs need to spawn with VIP+ players only in a match and if a player leaves the wolf needs to despawns and it needs to attack other players but if you can just get the wolf to spawn with ImagicalMine then I can do the rest

**Comment by EpicSteve33** [comment] 2016-04-26 00:28
@matthew4444 just submit a pull request if you can get it to work and Ill merge it. I will not give you any perms btw because I have trust issues lel

**Comment by RedEnder** [comment] 2016-04-26 00:30
Skrub

**Comment by EpicSteve33** [comment] 2016-04-26 00:32
there you go ender XD

**Comment by RedEnder** [comment] 2016-04-26 00:34
^ perfect!

**Comment by EpicSteve33** [comment] 2016-04-26 00:35
Lel

**Comment by RedEnder** [comment] 2016-04-26 00:36
@EpicSteve33 i looked at his code of Pets it spawns a Wolf but they dont follow players

**Comment by EpicSteve33** [comment] 2016-04-26 00:39
Ik I've already seen the plugin but the issue is I can't even get them to spawn at all

**Comment by RedEnder** [comment] 2016-04-26 00:40
Spawning them is so easy :P #Skrub

**Comment by EpicSteve33** [comment] 2016-04-26 00:43
Shhhhh

**Comment by EpicSteve33** [comment] 2016-04-26 00:44
Magiclel

**Comment by matthew4444** [comment] 2016-04-26 10:47
they tp now

**Comment by matthew4444** [comment] 2016-04-26 10:48
https://github.com/LostTeam/Pets

**Comment by matthew4444** [comment] 2016-04-26 10:49
idk phpp butu can ask the team to help

**Comment by RedEnder** [comment] 2016-04-26 13:35
@matthew4444 we need to move the wolfs on PlayerMoveEvent

**Comment by matthew4444** [comment] 2016-04-26 14:20
ask them

**Comment by EpicSteve33** [comment] 2016-04-26 14:50
@matthew4444 well im going to close this issue for now, maybe someday we will come back to this topic

**Closed** 2016-04-26 20:05 UTC
Labels: help wanted, invalid, question
